# Generated by Django 2.1.5 on 2020-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('localizacion', models.CharField(max_length=20, verbose_name='localizacion')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='ubicacion')),
                ('usuario', models.CharField(max_length=15, verbose_name='usuario')),
                ('sensor_id', models.CharField(max_length=30, verbose_name='sensor_id')),
                ('ip_sensor', models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip_sensor')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
            ],
        ),
    ]
