# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('localizacion', models.CharField(max_length=20, verbose_name='localizacion')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='ubicacion')),
                ('usuario', models.CharField(max_length=10, verbose_name='usuario')),
                ('sensor_id', models.CharField(max_length=10, verbose_name='sensor_id')),
            ],
        ),
    ]
