# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calor', '0002_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='ip_sensor',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip_sensor'),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='sensor_id',
            field=models.CharField(max_length=30, verbose_name='sensor_id'),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='usuario',
            field=models.CharField(max_length=15, verbose_name='usuario'),
        ),
    ]
